swagger: '2.0'
host: 0.0.0.0:8080
schemes:
  - http
info:
  version: 1.0.0
  title: NDEx Alignment Service
paths:
  /:
    get:
      summary: Show service information.
      responses:
        '200':
          description: Successful response
  /expand:
    post:
      summary: Takes a network (primary) and expands it with data from another network (secondary).
      parameters:
        - name: post_body
          in: body
          required: true
          schema:
            $ref: '#/definitions/CxPair'
      responses:
        '200':
          description: Successful response

definitions:
  CxPair:
    type: object
    properties:
      primary:
        type: array
        items:
          type: object
      secondary:
        type: array
        items:
          type: object

